# Generated by Django 3.0.8 on 2020-07-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridukaan', '0004_auto_20200719_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/no-image.jpeg', upload_to='images/'),
        ),
    ]
